# Generated by Django 4.2.4 on 2023-08-15 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='products/')),
                ('products_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('whole_weight', models.FloatField(default=1.0)),
                ('separate_weight', models.FloatField(default=1.0)),
                ('hometown', models.CharField(max_length=100)),
                ('organize', models.CharField(max_length=100)),
                ('seller_photo', models.ImageField(upload_to='products/')),
                ('person_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('bank_number', models.CharField(max_length=100)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
