# Generated by Django 4.2.4 on 2023-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='separate_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='whole_weight',
            field=models.FloatField(),
        ),
    ]
